
package schema

import (
	"errors"
)

func GetFhirResourceMap() map[string]string{
	return map[string]interface{}{
		"AppointmentResponse" : &AppointmentResponse{}, 
		"SubstancePolymer" : &SubstancePolymer{}, 
		"RiskEvidenceSynthesis" : &RiskEvidenceSynthesis{}, 
		"ImmunizationEvaluation" : &ImmunizationEvaluation{}, 
		"RequestGroup" : &RequestGroup{}, 
		"ChargeItem" : &ChargeItem{}, 
		"MolecularSequence" : &MolecularSequence{}, 
		"Appointment" : &Appointment{}, 
		"EventDefinition" : &EventDefinition{}, 
		"Slot" : &Slot{}, 
		"NutritionOrder" : &NutritionOrder{}, 
		"SupplyRequest" : &SupplyRequest{}, 
		"Library" : &Library{}, 
		"OperationOutcome" : &OperationOutcome{}, 
		"RiskAssessment" : &RiskAssessment{}, 
		"Substance" : &Substance{}, 
		"Location" : &Location{}, 
		"ImmunizationRecommendation" : &ImmunizationRecommendation{}, 
		"EvidenceVariable" : &EvidenceVariable{}, 
		"Contract" : &Contract{}, 
		"DeviceDefinition" : &DeviceDefinition{}, 
		"Provenance" : &Provenance{}, 
		"ExampleScenario" : &ExampleScenario{}, 
		"PaymentNotice" : &PaymentNotice{}, 
		"SearchParameter" : &SearchParameter{}, 
		"CarePlan" : &CarePlan{}, 
		"Goal" : &Goal{}, 
		"FamilyMemberHistory" : &FamilyMemberHistory{}, 
		"Subscription" : &Subscription{}, 
		"BiologicallyDerivedProduct" : &BiologicallyDerivedProduct{}, 
		"SubstanceProtein" : &SubstanceProtein{}, 
		"VerificationResult" : &VerificationResult{}, 
		"ResearchDefinition" : &ResearchDefinition{}, 
		"ImagingStudy" : &ImagingStudy{}, 
		"Organization" : &Organization{}, 
		"SubstanceSpecification" : &SubstanceSpecification{}, 
		"SubstanceSourceMaterial" : &SubstanceSourceMaterial{}, 
		"EnrollmentRequest" : &EnrollmentRequest{}, 
		"DetectedIssue" : &DetectedIssue{}, 
		"Device" : &Device{}, 
		"CareTeam" : &CareTeam{}, 
		"ExampleScenarioInstance" : &ExampleScenarioInstance{}, 
		"MedicinalProductIngredient" : &MedicinalProductIngredient{}, 
		"CatalogEntry" : &CatalogEntry{}, 
		"VisionPrescription" : &VisionPrescription{}, 
		"HealthcareService" : &HealthcareService{}, 
		"Composition" : &Composition{}, 
		"ClinicalImpression" : &ClinicalImpression{}, 
		"Measure" : &Measure{}, 
		"Medication" : &Medication{}, 
		"TestReport" : &TestReport{}, 
		"MessageDefinition" : &MessageDefinition{}, 
		"EnrollmentResponse" : &EnrollmentResponse{}, 
		"StructureDefinition" : &StructureDefinition{}, 
		"EpisodeOfCare" : &EpisodeOfCare{}, 
		"Observation" : &Observation{}, 
		"ValueSet" : &ValueSet{}, 
		"CoverageEligibilityResponse" : &CoverageEligibilityResponse{}, 
		"CommunicationRequest" : &CommunicationRequest{}, 
		"Evidence" : &Evidence{}, 
		"Schedule" : &Schedule{}, 
		"GraphDefinition" : &GraphDefinition{}, 
		"ObservationDefinition" : &ObservationDefinition{}, 
		"DocumentReference" : &DocumentReference{}, 
		"MedicinalProductUndesirableEffect" : &MedicinalProductUndesirableEffect{}, 
		"ChargeItemDefinition" : &ChargeItemDefinition{}, 
		"NamingSystem" : &NamingSystem{}, 
		"CodeSystem" : &CodeSystem{}, 
		"CompartmentDefinition" : &CompartmentDefinition{}, 
		"ResearchElementDefinition" : &ResearchElementDefinition{}, 
		"DiagnosticReport" : &DiagnosticReport{}, 
		"ExplanationOfBenefit" : &ExplanationOfBenefit{}, 
		"ResearchSubject" : &ResearchSubject{}, 
		"StructureMap" : &StructureMap{}, 
		"RelatedPerson" : &RelatedPerson{}, 
		"Binary" : &Binary{}, 
		"PlanDefinition" : &PlanDefinition{}, 
		"ServiceRequest" : &ServiceRequest{}, 
		"DeviceMetric" : &DeviceMetric{}, 
		"MedicinalProductPackaged" : &MedicinalProductPackaged{}, 
		"MeasureReport" : &MeasureReport{}, 
		"Questionnaire" : &Questionnaire{}, 
		"Linkage" : &Linkage{}, 
		"AllergyIntolerance" : &AllergyIntolerance{}, 
		"Encounter" : &Encounter{}, 
		"Immunization" : &Immunization{}, 
		"Bundle" : &Bundle{}, 
		"MedicinalProductIndication" : &MedicinalProductIndication{}, 
		"OperationDefinition" : &OperationDefinition{}, 
		"ImplementationGuide" : &ImplementationGuide{}, 
		"Patient" : &Patient{}, 
		"SupplyDelivery" : &SupplyDelivery{}, 
		"Account" : &Account{}, 
		"QuestionnaireResponse" : &QuestionnaireResponse{}, 
		"SubstanceReferenceInformation" : &SubstanceReferenceInformation{}, 
		"MedicationDispense" : &MedicationDispense{}, 
		"MedicinalProduct" : &MedicinalProduct{}, 
		"PractitionerRole" : &PractitionerRole{}, 
		"Invoice" : &Invoice{}, 
		"MedicationStatement" : &MedicationStatement{}, 
		"List" : &List{}, 
		"MedicinalProductManufactured" : &MedicinalProductManufactured{}, 
		"Parameters" : &Parameters{}, 
		"Flag" : &Flag{}, 
		"Specimen" : &Specimen{}, 
		"DeviceRequest" : &DeviceRequest{}, 
		"DeviceUseStatement" : &DeviceUseStatement{}, 
		"MedicationAdministration" : &MedicationAdministration{}, 
		"Consent" : &Consent{}, 
		"MedicationKnowledge" : &MedicationKnowledge{}, 
		"AdverseEvent" : &AdverseEvent{}, 
		"EffectEvidenceSynthesis" : &EffectEvidenceSynthesis{}, 
		"TerminologyCapabilities" : &TerminologyCapabilities{}, 
		"Condition" : &Condition{}, 
		"MedicinalProductPharmaceutical" : &MedicinalProductPharmaceutical{}, 
		"OrganizationAffiliation" : &OrganizationAffiliation{}, 
		"GuidanceResponse" : &GuidanceResponse{}, 
		"BodyStructure" : &BodyStructure{}, 
		"InsurancePlan" : &InsurancePlan{}, 
		"Practitioner" : &Practitioner{}, 
		"AuditEvent" : &AuditEvent{}, 
		"Coverage" : &Coverage{}, 
		"CoverageEligibilityRequest" : &CoverageEligibilityRequest{}, 
		"Person" : &Person{}, 
		"SubstanceNucleicAcid" : &SubstanceNucleicAcid{}, 
		"MessageHeader" : &MessageHeader{}, 
		"SpecimenDefinition" : &SpecimenDefinition{}, 
		"Communication" : &Communication{}, 
		"Group" : &Group{}, 
		"MedicinalProductContraindication" : &MedicinalProductContraindication{}, 
		"PaymentReconciliation" : &PaymentReconciliation{}, 
		"MedicinalProductInteraction" : &MedicinalProductInteraction{}, 
		"ClaimResponse" : &ClaimResponse{}, 
		"MedicinalProductAuthorization" : &MedicinalProductAuthorization{}, 
		"ActivityDefinition" : &ActivityDefinition{}, 
		"Media" : &Media{}, 
		"Procedure" : &Procedure{}, 
		"Task" : &Task{}, 
		"Endpoint" : &Endpoint{}, 
		"CapabilityStatement" : &CapabilityStatement{}, 
		"ConceptMap" : &ConceptMap{}, 
		"Basic" : &Basic{}, 
		"MedicationRequest" : &MedicationRequest{}, 
		"Claim" : &Claim{}, 
		"ResearchStudy" : &ResearchStudy{}, 
		"TestScript" : &TestScript{}, 
		"DocumentManifest" : &DocumentManifest{}, 
		}
}

func GetFhirResourceInstance(resource_name string) (interface{}, error) {
	FhirStructMap := GetFhirResourceMap()
	resource, ok := FhirStructMap[resource_name]
	if ok == true {
		return resource, nil
	}
	return resource, errors.New("Resource not found")
}